id: reply_chatwoot
namespace: chatwoot

tasks:
  - id: run_python
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    beforeCommands:
      - pip install -r requirements.txt
    commands:
      - python plugins/reply_chatwoot.py
    env:
      CHATWOOT_BODY: "{{ trigger.variables.body | toJson }}"
      CHATWOOT_BASE_URL: https://crm.inkantia.com.br
      CHATWOOT_API_TOKEN: Xic23HUotES1yRWgbVcKifij

triggers:
  - id: webhook_to_chatwoot
    type: io.kestra.plugin.core.trigger.Webhook
    key: chatwoot-incoming