id: reply_chatwoot
namespace: chatwoot

tasks:
  - id: run_python
    type: io.kestra.plugin.scripts.Python.Commands
    namespaceFiles:
      enabled: true
    beforeCommands:
      - pip install -r requirements.txt
    commands:
      - python plugins/reply_chatwoot.py
    env:
      CHATWOOT_BODY: "{{ trigger.body | toJson }}"

triggers:
  - id: webhook_to_chatwoot
    type: io.kestra.plugin.core.trigger.Webhook
    key: chatwoot-incoming